### ISSUE TITLE
Is this new manager compatible with StabilityMatrix? After restarting the manager and running in StabilityMatrix I always get this

### ISSUE THREAD

**Issue by andrej-ka** [Comfy-Org/manager-core#13]
Is this new manager compatible with StabilityMatrix? After restarting the manager and running in StabilityMatrix I always get this:

FETCH DATA from: D:\AI\Data\Packages\ComfyUI\custom_nodes\manager-core\.cache\1514988643_custom-node-list.json [DONE]
WAS Node Suite: Finished. Loaded 218 nodes successfully.

	"Great minds discuss ideas; average minds discuss events; small minds discuss people." - Eleanor Roosevelt

Traceback (most recent call last):
  File "D:\AI\Data\Packages\ComfyUI\main.py", line 262, in <module>
    loop.run_until_complete(run(server, address=args.listen, port=args.port, verbose=not args.dont_print_server, call_on_start=call_on_start))
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "D:\AI\Data\Packages\ComfyUI\main.py", line 167, in run
    await asyncio.gather(server.start_multi_address(addresses, call_on_start), server.publish_loop())
  File "D:\AI\Data\Packages\ComfyUI\server.py", line 840, in start_multi_address
    await site.start()
  File "D:\AI\Data\Packages\ComfyUI\venv\lib\site-packages\aiohttp\web_runner.py", line 119, in start
    self._server = await loop.create_server(
  File "asyncio\base_events.py", line 1519, in create_server
OSError: [Errno 10048] error while attempting to bind on address ('127.0.0.1', 8188): обычно разрешается только одно использование адреса сокета (протокол/сетевой адрес/порт)

**Comment by ltdrdata** [comment]
It means that another instance of ComfyUI is still running and has not been terminated.
