### ISSUE TITLE
stop connect to remote address when deployed in an Intranet

### ISSUE THREAD

**Issue by t00350320** [Comfy-Org/manager-core#7]
```
[2024-11-05 19:55] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[2024-11-05 19:55] Exception in thread Thread-2 (<lambda>):
[2024-11-05 19:55] Traceback (most recent call last):
[2024-11-05 19:55]   File "/usr/local/python3/lib/python3.10/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
[2024-11-05 19:55]     return await self._loop.create_connection(*args, **kwargs)
[2024-11-05 19:55]   File "/usr/local/python3/lib/python3.10/asyncio/base_events.py", line 1076, in create_connection
[2024-11-05 19:55]     raise exceptions[0]
[2024-11-05 19:55]   File "/usr/local/python3/lib/python3.10/asyncio/base_events.py", line 1060, in create_connection
[2024-11-05 19:55]     sock = await self._connect_sock(
[2024-11-05 19:55]   File "/usr/local/python3/lib/python3.10/asyncio/base_events.py", line 969, in _connect_sock
[2024-11-05 19:55]     await self.sock_connect(sock, address)
[2024-11-05 19:55]   File "/usr/local/python3/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect
[2024-11-05 19:55]     return await fut
[2024-11-05 19:55]   File "/usr/local/python3/lib/python3.10/asyncio/selector_events.py", line 541, in _sock_connect_cb
[2024-11-05 19:55]     raise OSError(err, f'Connect call failed {address}')
[2024-11-05 19:55] TimeoutError: [Errno 110] Connect call failed ('185.199.111.133', 443)
```
thanks

**Comment by t00350320** [comment]
> Is your network located in China? In that case, you may need a VPN. This will be resolved in the future through a reverse proxy. #10
Yes, as you said, it can connet this addres ip under a VPN env.
In my case, comfyui is deployed as a stable backend api server , so it's unnecessary to connect a remote address dynamicly. I guess a proper  configuration will stop this connection , but all workflows seem work fine in my backend server even with this error logs.

**Comment by t00350320** [comment]
> Is your network located in China? In that case, you may need a VPN. This will be resolved in the future through a reverse proxy. #10

Yes, as you said, it can connet this addres ip under a VPN env.
In my case, comfyui is deployed as a stable backend api server , so it's unnecessary to connect a remote address dynamicly. I guess a proper configuration will stop this connection , but all workflows seem work fine in my backend server even with this error logs.

**Comment by ltdrdata** [comment]
> > Is your network located in China? In that case, you may need a VPN. This will be resolved in the future through a reverse proxy. #10
> 
> Yes, as you said, it can connet this addres ip under a VPN env. In my case, comfyui is deployed as a stable backend api server , so it's unnecessary to connect a remote address dynamicly. I guess a proper configuration will stop this connection , but all workflows seem work fine in my backend server even with this error logs.

The remote connection is used to fetch or install custom node information from the internet and has no impact on workflow execution.
